wandb_version: 1

epochs:
  desc: null
  value: 10
batch_size:
  desc: null
  value: 64
learning_rate:
  desc: null
  value: 0.001
audio_dir:
  desc: null
  value: ../data/Crema
sample_rate:
  desc: null
  value: 16000
num_samples:
  desc: null
  value: 22050
n_fft:
  desc: null
  value: 1024
hop_length:
  desc: null
  value: 512
n_mels:
  desc: null
  value: 64
model:
  desc: null
  value: cnn
dataset:
  desc: null
  value: crema
_wandb:
  desc: null
  value:
    python_version: 3.9.5
    cli_version: 0.16.6
    framework: huggingface
    huggingface_version: 4.38.2
    is_jupyter_run: true
    is_kaggle_kernel: true
    start_time: 1714091146.0
    t:
      1:
      - 1
      - 11
      - 41
      - 49
      - 55
      2:
      - 1
      - 11
      - 41
      - 49
      - 55
      3:
      - 1
      - 2
      - 16
      - 23
      - 61
      4: 3.9.5
      5: 0.16.6
      6: 4.38.2
      8:
      - 1
      - 2
      - 5
      13: linux-x86_64
